export const IMAGES = {
    logo: {
        jackYak: '/images/logo/jack-yak-logo.png',
    },
    home: {
        heroBg: '/images/home/hero-bg.png',
        heroSecondary: '/images/home/hero-secondary.png',
        mountainDivider: '/images/home/mountain-divider.png',
        aboutJackyak: '/images/home/about-jackyak.png',
        discoverNepal1: '/images/home/discover-nepal-1.png',
        discoverNepal2: '/images/home/discover-nepal-2.png',
        provincesMap: '/images/home/nepal-provinces-map.png',
        mapProvinces: {
            'sudur-pashchim': '/images/home/map/provinces/sudur-pashchim.png',
            karnali: '/images/home/map/provinces/karnali.png',
            lumbini: '/images/home/map/provinces/lumbini.png',
            gandaki: '/images/home/map/provinces/gandaki.png',
            bagmati: '/images/home/map/provinces/bagmati.png',
            madhesh: '/images/home/map/provinces/madhesh.png',
            koshi: '/images/home/map/provinces/koshi.png',
        },
        trekkerYak: '/images/home/trekker-yak-silhouette.png',
    },
    destination: {
        amaDablam: '/images/destination/ama-dablam-panorama.png',
        hero: {
            amaDablam: '/images/destination/hero/ama_dablam.png',
            chitwan: '/images/destination/hero/chitwan.png',
            pokhara: '/images/destination/hero/pokhara.png',
            sun: '/images/destination/hero/background-sun.png',
        },
        swayambhuStupa: '/images/destination/swayambhu-stupa.png',
        stupaPanorama: '/images/destination/stupa-mountain-panorama.png',
        journey: '/images/destination/journey.png',
        journeyMobile: '/images/destination/journey-mobile.png',
        journeyMountain: '/images/destination/journey-mountain.png',
        journeyMobileMountain:
            '/images/destination/journey-mobile-mountain.png',
        yakMascot: '/images/destination/yak-mascot.png',
        mountEverest: '/images/destination/mount-everest.png',
        langtangMountain: '/images/destination/langtang-mountain.png',
        pokharaLake: '/images/destination/pokhara-lake.png',
        mardiHimal: '/images/destination/mardi-himal.png',
        upperMustang: '/images/destination/upper-mustang.png',
        chitwanRhino: '/images/destination/chitwan-rhino.png',
        kathmanduTemple: '/images/destination/kathmandu-temple.png',
        icons: {
            all: '/images/destination/icons/icon-all.png',
            trekking: '/images/destination/icons/icon-trekking.png',
            safari: '/images/destination/icons/icon-safari.png',
            spiritual: '/images/destination/icons/icon-spiritual.png',
            heritage: '/images/destination/icons/icon-heritage.png',
            lakes: '/images/destination/icons/icon-lakes.png',
        },
        featured: {
            elephantSafari: '/images/destination/featured/elephant_safari.png',
            jeepSafari: '/images/destination/featured/jeep_safari.png',
            canoeSafari: '/images/destination/featured/canoe_safari.png',
            birdWatchingSafari:
                '/images/destination/featured/birdwatching_safari.png',
            crocodileWatching:
                '/images/destination/featured/crocodilewatching.png',
            tigerWatching: '/images/destination/featured/tiger_watching.png',
        },
    },
    featured: {
        tilichoLake: '/images/featured/tilicho-lake.png',
        everestPrayerFlags: '/images/featured/everest-prayer-flags.png',
        gokyoLake: '/images/featured/gokyo-lake.png',
    },
    guide: {
        everest: '/images/guide/guide_first.png',
        pokhara: '/images/guide/guide_second.png',
        chitwan: '/images/guide/guide_third.png',
    },
    viewAll: {
        everest: '/images/view-all/everest.png',
        swayambhuStupa: '/images/view-all/swayambhu-stupa.png',
        pokharaLakeside: '/images/view-all/pokhara-lakeside.png',
        langtangValley: '/images/view-all/langtang-valley.png',
        mardiHimal: '/images/view-all/mardi-himal.png',
        upperMustang: '/images/view-all/upper-mustang.png',
        chitwanSafari: '/images/view-all/chitwan-safari.png',
        kathmanduDurbar: '/images/view-all/kathmandu-durbar.png',
        stupaPanorama: '/images/view-all/stupa-panorama.png',
        elephantSafari: '/images/view-all/elephant-safari.png',
        jeepSafari: '/images/view-all/jeep-safari.png',
        canoeSafari: '/images/view-all/canoe-safari.png',
        tilichoLake: '/images/view-all/tilicho-lake.png',
        everestFlags: '/images/view-all/everest-flags.png',
        gokyoLakes: '/images/view-all/gokyo-lakes.png',
        mounteverestFirst: '/images/view-all/mounteverest_1.png',
        pokharaFirst: '/images/view-all/pokhara_1.png',
        chitwanFirst: '/images/view-all/chitwan_1.png',
    },
    about: {
        pokharaLakeside: '/images/about/pokhara.png',
        chitwanSafari: '/images/about/chitwan.png',
        luklaFlight: '/images/about/desktop_plane.png',
        travelerAvatar: '/images/about/traveler-avatar.png',
        hero: '/images/about/hero/about-hero.png',
        heroSecond: '/images/about/hero/about-hero-second.png',
        difference: '/images/about/about-difference.png',
        differenceMobile: '/images/about/about-difference-mobile.png',
        plan: '/images/about/about-plan.png',
        heroSlides: [
            '/images/about/hero/about-hero-1.png',
            '/images/about/hero/about-hero-2.png',
            '/images/about/hero/about-hero-3.png',
        ],
    },
    icons: {
        advanture: '/images/about/icons/advanture_activities.png',
        localCommunication: '/images/about/icons/local_communication.png',
        nationalPark: '/images/about/icons/national_park.png',
        travelling: '/images/about/icons/traveling.png',
        wildlife: '/images/about/icons/wildlife_experience.png',
    },
    itinerary: {
        icons: {
            stay: '/images/itinerary/icons/icon-stay.png',
            meals: '/images/itinerary/icons/dinner.png',
        },
        hero: '/images/itinerary/hero/143d24e9d4ef2e765e75fbe263dfdb8cfa94170f.jpg',
        galleryThumbs: [
            '/images/itinerary/hero/27edfe65c09692847041bb16d30d87d8f49346e4.jpg',
            '/images/itinerary/hero/6b96a96cd3ecdd1a1c94634821413d615bb94441.jpg',
            '/images/itinerary/hero/8b68c4df8683f79f38b958532662ce0248180a42.jpg',
        ],
        dayThumb: '/images/destination/kathmandu-temple.png',
        videoPoster:
            '/images/itinerary/hero/8b68c4df8683f79f38b958532662ce0248180a42.jpg',
        reviewerAvatar: '/images/about/traveler-avatar.png',
        reviewPhotos: [
            '/images/itinerary/reviews/00c26be59e7a15b8c98eb58a907d3be47fb6542f.jpg',
            '/images/itinerary/reviews/02483580c448ee13dfa0efe32505f7c0f8df971d.jpg',
            '/images/itinerary/reviews/0724245dde0407ef4d8d11f03f1c6a4e045b34c8.jpg',
            '/images/itinerary/reviews/1a2b4bbdacdc3875feeb20f56483db9cee9d6cc7.jpg',
            '/images/itinerary/reviews/219cef2d24529573ab5b4f71223a12e416e896e3.jpg',
            '/images/itinerary/reviews/2b6a5fd9e8fa1bb271f1cd8309b1f2d70a223cb2b.jpg',
            '/images/itinerary/reviews/8339290b1242156ca73bd6cae64c22c5fb0f6dc3.jpg',
            '/images/itinerary/reviews/846c1e67cf9ebe0c0ef4496de3a12f9e3fbb33f5b.jpg',
            '/images/itinerary/reviews/c65e646b70f1d6fa76b8b4be3345ba4fbb5f0f01.jpg',
            '/images/itinerary/reviews/faa32674ad456c9c0df285cfb601f0ff2d41ca61.jpg',
        ],
    },
    login: {
        panel: '/images/login/login.png',
    },
} as const;

export type Images = typeof IMAGES;
