import { clsx, type ClassValue } from 'clsx';
import { extendTailwindMerge } from 'tailwind-merge';

// Mirror of the custom tokens in resources/css/app.css (@theme).
// tailwind-merge only knows default Tailwind utilities — without this,
// our custom `text-*` sizes fall in the same bucket as `text-*` colors
// and silently eat each other inside cn(), e.g.
// cn('text-2xl-3xl', 'text-text-primary') → 'text-text-primary' (size lost).
// Keep this list in sync with @theme when adding new tokens.
const twMerge = extendTailwindMerge({
    extend: {
        theme: {
            text: [
                '2xs',
                'xs-sm',
                'xs-md',
                'about-highlight',
                'sm-base',
                'base-md',
                'sm-md',
                'md-lg',
                'md-xl',
                'lg-xl',
                'xl-2xl',
                '2xl-3xl',
                '3xl-4xl',
                'hero',
                'display',
                'about-display',
                'section-xl',
                'modal',
                'journey',
                'display-lg',
            ],
            leading: [
                'hero',
                'journey',
                'display-lg',
                'about-display',
                'section-xl',
                'about',
                'card-meta',
                'card-title',
                'card-desktop',
                'card-display',
                'itinerary-19',
                'itinerary-22',
                'itinerary-23',
                'itinerary-25',
                'itinerary-26',
                'itinerary-27',
                'itinerary-28',
                'about-30',
                'about-32',
                'itinerary-33',
            ],
            font: ['manrope', 'display', 'poppins', 'roboto'],
            color: [
                'navy',
                'navy-light',
                'navy-gradient',
                'teal',
                'orange',
                'blue-icon',
                'text-primary',
                'text-white',
                'bg-cream',
                'bg-warm',
                'bg-placeholder',
                'progress',
                'ember',
                'brand',
                'ink',
                'cta',
                'cta-accent',
                'cta-ember',
                'surface-warm',
                'surface-cream',
                'icon-accent',
                'quote-blush',
                'canvas',
                'steel',
                'pine',
                'frost',
                'frost-line',
                'fog',
                'divider',
                'midnight',
                'mist',
                'quiz-line',
                'hairline',
                'subtle',
                'haze',
                'abyss',
                'slate-text',
                'pale',
                'strike',
                'star-empty',
                'deep-teal',
                'line-soft',
                'sky-tint',
                'sky-line',
                'wa',
                'badge-teal',
                'card-line',
                'gallery-shade',
                'count-overlay',
                'count-overlay-active',
                'ash',
                'review-ink',
                'review-body',
                'chart-line',
                'chart-fill',
                'slate-mute',
                'graph-title',
            ],
            radius: [
                'card',
                'image',
                'dest-card',
                'card-sm',
                'dest-image',
                'dest-badge',
                'dest-panel',
                'immersive',
                'itinerary-card',
                'itinerary-thumb',
                'itinerary-cta',
                'gallery-tile',
            ],
            blur: ['hero-sm', 'hero-lg'],
            shadow: ['card'],
            spacing: [
                'card-w',
                'card-h',
                'logo',
                'logo-w',
                'sidebar',
                'hamburger',
                'hero-line',
                'dest-card-w',
                'dest-card-h',
                'feat-card-h',
                'itinerary-hero-h',
                'itinerary-thumb-h',
                'day-thumb-w',
                'day-thumb-h',
                'day-text-w',
                'day-card-h',
                'day-card-desktop-h',
                'day-thumb-desktop-w',
                'day-thumb-desktop-h',
                'cta-thumb-w',
                'cta-thumb-h',
                'cta-button-w',
                'graph-h',
                'graph-card-w',
            ],
        },
    },
});

export function cn(...inputs: ClassValue[]) {
    return twMerge(clsx(inputs));
}
